Repository apinf/openapi-space, pull requests merged in 2018-06, with the labels that each got.

#28 Fix space in URL
  space/models/api.py
Labels: in progress

#24 Add file explaining technology choices etc.
  TECH.md
Labels: meta, ready for review

#32 Force correct flake8 version
  requirements/ci.txt
Labels: in progress, ready for review
